// <auto-generated />
using System;
using LostAndFound.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostAndFound.Migrations
{
    [DbContext(typeof(LostAndFoundContext))]
    [Migration("20240312144859_Update Table")]
    partial class UpdateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LostAndFound.Models.LostInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AcquirerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acquirer_name");

                    b.Property<DateTime?>("FoundDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("found_date");

                    b.Property<DateTime>("LostDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("lost_date");

                    b.Property<string>("LostItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lost_item");

                    b.Property<string>("LostLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lost_location");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner_name");

                    b.HasKey("Id");

                    b.ToTable("lost_infos");
                });
#pragma warning restore 612, 618
        }
    }
}
